# Generated by Django 5.2.7 on 2025-11-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='titlle',
            new_name='title',
        ),
    ]
